Also pass positional arguments along to ConnectionDurableDict
Otherwise, the preceding promise can't be kept:

    Functions just like you'd expect it::

        mydict = RedisDict('my_redis_key', Redis())
        mydict['test']
        >>> 'bar' #doctest: +SKIP

Both arguments are positional. This actually throws a:

    TypeError: __init__() takes exactly 1 argument (3 given)